### ISSUE TITLE
How about adding hypothesizer that supports gating

### ISSUE THREAD

**Issue by Huang-Chuan** [dstl/Stone-Soup#144]
In my case(mechanical scanning radar), approximately 50 or more targets are in the region of surveillance simultaneously, which rendered GNN association impossible because of the combination explosion problem.
  
  I think association algorithm speeds up by dividing surveillance region into several sections and only considering hypothesis which associates detections that are in nearby sections.

**Comment by sdhiscocks** [comment]
Some improved approaches to association would be useful.

I've found much better performance from using #126, but whilst making GNN faster, doesn't solve the issue of gating to avoid unnecessary hypotheses being generated.

I've just created (#145), a hypothesiser that uses a [kd-tree](https://en.wikipedia.org/wiki/K-d_tree) for detections, and used to wrap existing hypothesisers to provide gating. There's some overhead in constructing the tree, but performance reward soon outweighs this. I'd be interested if you find this improves things in your scenario @Huang-Chuan?

It may also make sense to have a tree that is track based instead, but think this will be a limit more awkward to implement due to current layout of the framework.

**Comment by sdhiscocks** [comment]
@Huang-Chuan Have you tried the 2d assignment GNN in #126? This is orders of magnitude faster than the default GNN.

**Comment by Huang-Chuan** [comment]
Not yet. But I did read the paper by Dr. Crouse where he suggested clustering when problem size is over 10. Is there any way to do this?

**Comment by sdhiscocks** [comment]
Hopefully you'll find the 2D assignment GNN may be fast enough for 50 targets, but it is also dependent on number of detections.

Do you have the title or link to their paper?

**Comment by Huang-Chuan** [comment]
Link: https://ieeexplore.ieee.org/document/7842561
Title: Computation of Target-Measurement Association Probabilities Using the Matrix Permanent 

I think 2D assignment GNN uses exactly the algorithm proposed in this paper where the author gives performance evaluation on different number of targets. The time it takes increases from 1.51ms for 1 target to 2.6s for 10 targets.

**Comment by sdhiscocks** [comment]
Thanks @Huang-Chuan. So the 2D assignment that is used in #126 is outlined in the paper [_On implementing 2D rectangular assignment algorithms_](https://ieeexplore.ieee.org/document/7738348) by @DavidFCrouse, which David kindly converted into Python for us from the [Tracker Component Library](https://github.com/USNavalResearchLaboratory/TrackerComponentLibrary).

You'll see from the paper, the performance expected is significantly better.

**Comment by Huang-Chuan** [comment]
Forgive me for carelessly referring to an irrelevant paper. I'll read that paper and see if it works.
