### ISSUE TITLE
Unscented transform doesn't know about relative offsets

### ISSUE THREAD

**Issue by jmbarr** [dstl/Stone-Soup#255]
In mucking around with the UKF, I've observed odd behaviour when sensors are offset from 0,0. The mean is transformed back to its original position ok but the relative orientation of the sigma points is mucked up. When I've got more time I'll do some plots but I wondered if anyone had observed similar...

**Comment by jmbarr** [comment]
https://gist.github.com/jmbarr/0fb37dc52b397067f2ad9552bc219440
for an example notebook. 

(I think.)

**Comment by sglvladi** [comment]
@jmbarr I've had a look and this issue seems to occur because of the use of integers in specifying the state vector elements of the states. See [here](https://gist.github.com/sglvladi/7160a87b9a71058caf3c640589943238) for a fix.

I have also written a gist which demonstrates where the issue occurs and discusses potential fixes. See [here](https://gist.github.com/sglvladi/8d1ff25944876bdbb6caf4058ca7cfe5)

**Comment by jmbarr** [comment]
Ah, excellent; well found. 

So there's a quick fix (initialise in the 'correct' type) but, there's more of a conversation to be had about how StateVectors preserve/cast their types. Fold that into #186 and #277 maybe?
