### ISSUE TITLE
Updates have broken the demonstration in the documentation on tracking using groundtruth ADS-B data

### ISSUE THREAD

**Issue by LyceanEM** [dstl/Stone-Soup#620]
I have been working on modelling a measured reflector based radar, and writing a beamshape class and radar variant class in stonesoups style, but in setting up my test example using ADS-B data, the demonstration in your documentation no longer works with the codebase. I have the ground truth working, and altered the folium code so that it uses the default map tiles as the ones used in your example are no longer supported. However, no detections or tracks occur when the radar range is 100km, and if I extend the range a substantial amount then detections and tracks occur but bear no relationship to the ground truth.

I would appreciate your input on the issue.
[openskyrewrite.txt](https://github.com/dstl/Stone-Soup/files/8408397/openskyrewrite.txt)

**Comment by hpritchett-dstl** [comment]
Sorry for the late response on this.

I had a look at the code you supplied, and I think the issue lies in specifying the positional mapping in line 63.

Instead of platform = FixedPlatform(platformState, (0, 1, 2)), try using:
                 platform = FixedPlatform(platformState, (0, 2, 4))

Also, currently the location of the sensor (line 42) and the folium circle / marker (line 137 and 142 respectively) don't coincide. Make sure they're the same so the map displays the sensor location / FOV correctly.

Hopefully this works for you, if not please let me know!

Thanks,
Henry

**Comment by LyceanEM** [comment]
Hello Henry

Thank you for your response. Sure enough that has completely fixed the issue. I had thought I had updated the example to the new syntax correctly, I suppose I just misunderstood how the positional mapping is specified.
